import {
  ApartmentOutlined,
  AppstoreOutlined,
  AuditOutlined,
  BankOutlined,
  BarChartOutlined,
  BarsOutlined,
  BellOutlined,
  BookOutlined,
  BulbOutlined,
  CalendarOutlined,
  CarryOutOutlined,
  CheckCircleOutlined,
  CheckSquareOutlined,
  ClockCircleOutlined,
  ClusterOutlined,
  CommentOutlined,
  ContainerOutlined,
  ControlOutlined,
  CrownOutlined,
  DashboardOutlined,
  DatabaseOutlined,
  DeploymentUnitOutlined,
  DiffOutlined,
  DollarOutlined,
  DownloadOutlined,
  EditOutlined,
  ExperimentOutlined,
  ExportOutlined,
  EyeOutlined,
  FieldTimeOutlined,
  FileDoneOutlined,
  FileExcelOutlined,
  FileOutlined,
  FilePdfOutlined,
  FileProtectOutlined,
  FileSearchOutlined,
  FileTextOutlined,
  FilterOutlined,
  FlagOutlined,
  FolderOpenOutlined,
  FolderOutlined,
  FormOutlined,
  FundOutlined,
  GlobalOutlined,
  HistoryOutlined,
  HomeOutlined,
  IdcardOutlined,
  ImportOutlined,
  InboxOutlined,
  KeyOutlined,
  LineChartOutlined,
  LinkOutlined,
  LockOutlined,
  MailOutlined,
  MenuOutlined,
  MessageOutlined,
  NotificationOutlined,
  NumberOutlined,
  OrderedListOutlined,
  PaperClipOutlined,
  PartitionOutlined,
  PercentageOutlined,
  PieChartOutlined,
  PrinterOutlined,
  ProfileOutlined,
  ProjectOutlined,
  PushpinOutlined,
  QuestionCircleOutlined,
  ReadOutlined,
  ReconciliationOutlined,
  RocketOutlined,
  SafetyCertificateOutlined,
  SafetyOutlined,
  ScheduleOutlined,
  SearchOutlined,
  SettingOutlined,
  SnippetsOutlined,
  SolutionOutlined,
  SoundOutlined,
  StarOutlined,
  TableOutlined,
  TagsOutlined,
  TeamOutlined,
  ToolOutlined,
  TrophyOutlined,
  UnorderedListOutlined,
  UploadOutlined,
  UserAddOutlined,
  UserOutlined,
  UserSwitchOutlined,
  UsergroupAddOutlined,
  WalletOutlined,
  WarningOutlined,
} from '@ant-design/icons-vue'
import type { Component } from 'vue'

/*
 * 메뉴의 icon 필드는 ant-design-vue 아이콘 컴포넌트명을 문자열 그대로 담는다(예: 'SettingOutlined').
 * 관리자 사이드바에서 이 문자열을 실제 컴포넌트로 바꾸기 위한 허용 목록이다.
 *
 * 네임스페이스(`import * as`)로 이름을 찾으면 아이콘 세트 전체(약 790개)가 번들에 들어가고,
 * 지원자 화면까지 포함된 공통 청크로 끌려 올라간다(측정: index 청크 +1,057kB / gzip +175kB).
 * 동적 import로 분리해도 지원자 화면이 같은 패키지를 정적 import 하고 있어 한 청크로 합쳐진다.
 * 그래서 필요한 아이콘만 명시적으로 import 해 트리셰이킹이 되도록 한다.
 *
 * 후속 슬라이스의 메뉴 관리 화면 아이콘 피커는 이 목록을 선택지로 그대로 쓴다.
 * 즉 이 목록이 "메뉴에 지정 가능한 아이콘"의 단일 출처다. 아이콘을 늘리려면 여기에 추가한다.
 */
export const ADMIN_MENU_ICONS: Record<string, Component> = {
  ApartmentOutlined,
  AppstoreOutlined,
  AuditOutlined,
  BankOutlined,
  BarChartOutlined,
  BarsOutlined,
  BellOutlined,
  BookOutlined,
  BulbOutlined,
  CalendarOutlined,
  CarryOutOutlined,
  CheckCircleOutlined,
  CheckSquareOutlined,
  ClockCircleOutlined,
  ClusterOutlined,
  CommentOutlined,
  ContainerOutlined,
  ControlOutlined,
  CrownOutlined,
  DashboardOutlined,
  DatabaseOutlined,
  DeploymentUnitOutlined,
  DiffOutlined,
  DollarOutlined,
  DownloadOutlined,
  EditOutlined,
  ExperimentOutlined,
  ExportOutlined,
  EyeOutlined,
  FieldTimeOutlined,
  FileDoneOutlined,
  FileExcelOutlined,
  FileOutlined,
  FilePdfOutlined,
  FileProtectOutlined,
  FileSearchOutlined,
  FileTextOutlined,
  FilterOutlined,
  FlagOutlined,
  FolderOpenOutlined,
  FolderOutlined,
  FormOutlined,
  FundOutlined,
  GlobalOutlined,
  HistoryOutlined,
  HomeOutlined,
  IdcardOutlined,
  ImportOutlined,
  InboxOutlined,
  KeyOutlined,
  LineChartOutlined,
  LinkOutlined,
  LockOutlined,
  MailOutlined,
  MenuOutlined,
  MessageOutlined,
  NotificationOutlined,
  NumberOutlined,
  OrderedListOutlined,
  PaperClipOutlined,
  PartitionOutlined,
  PercentageOutlined,
  PieChartOutlined,
  PrinterOutlined,
  ProfileOutlined,
  ProjectOutlined,
  PushpinOutlined,
  QuestionCircleOutlined,
  ReadOutlined,
  ReconciliationOutlined,
  RocketOutlined,
  SafetyCertificateOutlined,
  SafetyOutlined,
  ScheduleOutlined,
  SearchOutlined,
  SettingOutlined,
  SnippetsOutlined,
  SolutionOutlined,
  SoundOutlined,
  StarOutlined,
  TableOutlined,
  TagsOutlined,
  TeamOutlined,
  ToolOutlined,
  TrophyOutlined,
  UnorderedListOutlined,
  UploadOutlined,
  UserAddOutlined,
  UserOutlined,
  UserSwitchOutlined,
  UsergroupAddOutlined,
  WalletOutlined,
  WarningOutlined,
}

export const resolveAntIcon = (iconName: string | null | undefined): Component | null => {
  if (!iconName) {
    return null
  }

  return ADMIN_MENU_ICONS[iconName] ?? null
}

/*
 * 아이콘이 없거나 허용 목록에 없는 이름이어도 아이콘 자리를 유지해야 라벨 정렬이 흐트러지지 않는다.
 */
export const resolveAntIconOrFallback = (iconName: string | null | undefined): Component => {
  return resolveAntIcon(iconName) ?? AppstoreOutlined
}
