package com.shinyoung.recruit.enumeration;

public enum AttachmentType {
    RESUME,
    TRANSCRIPT,
    GRADUATION_CERTIFICATE,
    CAREER_CERTIFICATE,
    CAREER_DESCRIPTION,
    EMPLOYMENT_CERTIFICATE,
    CERTIFICATE_PROOF,
    LANGUAGE_SCORE_REPORT,
    PORTFOLIO,
    ETC
}
